[tool.black]
line-length = 79
skip-string-normalization = true
target-version = ['py39']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | migrations
)
'''

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "card_manager.settings"
python_files = "test_*.py"
addopts = ["-vv", "--reuse-db", "--disable-warnings"]